# Models configuration for bizCon benchmark
# This file defines the models to be included in benchmark evaluations

models:
  - provider: openai
    name: gpt-4
    temperature: 0.7
    max_tokens: 2048
    parameters:
      seed: 42
    
  - provider: openai
    name: gpt-3.5-turbo
    temperature: 0.7
    max_tokens: 2048
    parameters:
      seed: 42
    
  - provider: anthropic
    name: claude-3-sonnet
    temperature: 0.7
    max_tokens: 2048
    
  - provider: anthropic
    name: claude-3-haiku
    temperature: 0.7
    max_tokens: 2048
    
  - provider: mistral
    name: mistral-large
    temperature: 0.7
    max_tokens: 2048